### ISSUE TITLE
Yokogawa GS200 driver does not detect correct mode on connection

### ISSUE THREAD

**Issue by spauka** [QCoDeS/Qcodes#1408] opened 2018-12-04 00:11 UTC
When reconnecting to a yokogawa GS200 set to current mode, the driver does not correctly detect the state and does not allow setting a current output.

There is then no way to change the mode in software without either:
 - Turning off output and changing mode
 - Changing private variables in the driver

### Steps to reproduce
1. Set yokogawa to current output on front panel of via qcodes
2. Reconnect to the instrument
3. Try setting a current output: `yoko.current(1e-3)`

### Expected behaviour
Instrument mode should be detected at connection

### System
Windows 10
Qcodes f8afd731a76587af1580dd89d5571936fe14093f

**Comment by FarBo** [comment] 2020-09-23 06:50
The issue is fixed in the PR #2143

**Closed by FarBo** 2020-09-23 06:50 UTC
