### ISSUE TITLE
N52xx.py driver bug

### ISSUE THREAD

**Issue by alebrunoeth** [QCoDeS/Qcodes#3054] opened 2021-05-26 13:23 UTC
### Steps to reproduce
1.Run python code from notebook and sweep over around 12500 * n points or more (n integer).
2.Wait for measurements.
3.Plot measurement results and analyse trace result.

code (also attached in the text file):

```python
import numpy as np
from matplotlib import pyplot as plt
import qcodes

qcodes.Instrument.close_all() 
from qcodes.instrument_drivers.Keysight.N52xx import PNABase
VNA=PNABase(name = 'test', address='TCPIP0::Localhost::hislip0::INSTR',min_freq=10e6,max_freq=20e9,min_power=-100,max_power=0,nports=2)

probe_start  = 4e9
probe_stop   = 8e9

probe_pwr = 0 # in dBm
num_points=20001
if_bandwidth=10000
timeout=100000

VNA.set('power',probe_pwr)
VNA.set('start',probe_start)
VNA.set('stop',probe_stop)
VNA.set('points',num_points)
VNA.set('timeout',timeout)
VNA.set('if_bandwidth',if_bandwidth)
VNA.set('trace','S21')
VNA.get_idn()

VNA.traces.tr1.run_sweep()
values=VNA.real()+1j*VNA.imaginary()
coordinates=np.linspace(probe_start,probe_stop,num_points)
plt.plot(coordinates, 20 * np.log10(np.abs(values)))

print(values[12400:12415])
plt.plot(coordinates[12400:12415],values[12400:12415])
```

### Expected behaviour
Result is just the expected trace response.

### Actual behaviour
Every (approximately) 12500 points, an outlier occurs composed of four points (with amplitude respectively close to 1e-45, 2, 1e-43, 1e-7). This is not from the physical measurement and we would like to not use any functions to delete this manually. (In our case the first points are number 12405 to 12408)
### System
**operating system**
Windows 10 64-bit
**qcodes version**
0.23.0

[PNABase_bug.txt](https://github.com/QCoDeS/Qcodes/files/6546965/PNABase_bug.txt)

**Comment by astafan8** [comment] 2021-05-26 13:28
@alebrunoeth do you mind attaching a plot with that data and those outliers (as an image)? for a visual aid

**Comment by alebrunoeth** [comment] 2021-05-26 13:30
dB plot over whole spectrum.
![image](https://user-images.githubusercontent.com/61413844/119667964-6b755200-be3f-11eb-914d-2e62a9bcb2bf.png)
zoomed plot in absolute value
![image](https://user-images.githubusercontent.com/61413844/119668196-a1b2d180-be3f-11eb-98ec-2d7a1bbd4490.png)

**Comment by alebrunoeth** [comment] 2021-05-26 13:32
dB plot using 60000 points (4 features appear)

![image](https://user-images.githubusercontent.com/61413844/119668577-f8201000-be3f-11eb-8a92-318525eac88e.png)

**Comment by jenshnielsen** [comment] 2021-05-26 13:44
@spauka I think you originally wrote this driver. Have you ever seen anything like this? 

@alebrunoeth before doing anything else I would suggest that you ensure that the instrument is updated to the latest firmware version. It seems at least possible that this is an issue with the instrument firmware

**Comment by alebrunoeth** [comment] 2021-05-27 06:30
I already did update the firmware

**Comment by jenshnielsen** [comment] 2021-05-27 07:36
@alebrunoeth thanks for the update unfortunately I don't think the fact that the issue is not present in the gui can be used to establish where the issue is. The driver is using `CALC:DATA? FDATA` to read back the data from the instrument. It will require some debugging to establish why the data contains some wrong samples but it seems most likely that those datapoints are already present in the data read back at this stage

**Comment by alebrunoeth** [comment] 2021-05-27 07:56
Thank you, I will try and debug and try to see if the problem arises while using VisaImplementation as well

**Comment by spauka** [comment] 2021-05-27 11:21
@jenshnielsen @alebrunoeth I have indeed seen this same issue - although it was on an Infinium scope and not on a PNA. The issue arose when we tried to transfer >100000 pts from the scope in a single measurement. It seemed like the instrument was inserting some random characters in the middle of the data.

I'm just asking around to ask if we had a better solution than to break the measurement down into multiple smaller acquisitions 😆

**Comment by spauka** [comment] 2021-12-15 03:03
Hi @alebrunoeth - just wondering if you're still seeing this issue? I'm not able to reproduce it any more on my scope of DSO so it may have been fixed somewhere?

**Comment by spauka** [comment] 2023-06-02 05:36
@jenshnielsen I'm regularly taking 50001 point traces on the PNA and not seeing this issue. I suggest we can close it?

**Comment by jenshnielsen** [comment] 2023-06-02 11:33
@spauka agreed @alebrunoeth if you still can reproduce please let us know and we can reopen

**Closed by jenshnielsen** 2023-06-02 11:33 UTC
